import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";

const moods = {
  japandi: { title: "Japandi Poolhouse Retreat", label: "Japandi calm", sub: "stilte, balans, warm minimalisme", material: "thermowood", roof: "flat", image: "https://images.unsplash.com/photo-1600566753151-384129cf4e3e?auto=format&fit=crop&w=900&q=80" },
  villa: { title: "Luxury Villa Outdoor Room", label: "Luxe villa", sub: "status, avondlicht, ontvangst", material: "black", roof: "canopy", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80" },
  rural: { title: "Landelijke Eik-Douglas Lodge", label: "Landelijk", sub: "authentiek, warm, familiaal", material: "oak", roof: "gable", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80" },
  wellness: { title: "Private Wellness Garden Suite", label: "Wellness", sub: "sauna, rust, zachte verlichting", material: "stone", roof: "flat", image: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=900&q=80" }
};
const modules = [["terrace", "Terras", 4200], ["storage", "Berging", 5200], ["sauna", "Sauna", 11800], ["kitchen", "Buitenkeuken", 8900], ["bike", "Fietsenstalling", 2600], ["lounge", "Lounge", 6400], ["carport", "Carport", 7600]];
const state = { mood: "japandi", feeling: "calm", buildingType: "poolhouse", roof: "flat", material: "thermowood", windowStyle: "panoramic", width: 6, depth: 4, glass: 45, budget: 42000, activeModules: new Set(["terrace", "lounge"]), night: false, rotate: true };
const ids = ["moodChoices", "moduleChoices", "feeling", "width", "depth", "glass", "budget", "buildingType", "roof", "material", "windowStyle", "totalPrice", "priceDelta", "conceptTitle", "dimensions", "aiHeadline", "aiText", "budgetFit", "upgrade", "saving", "lifestyleVisual", "lifestyleText", "dayNightBtn", "rotateBtn", "shareBtn", "saveBtn", "compareBtn", "appointmentBtn", "arBtn"];
const els = Object.fromEntries(ids.map((id) => [id, document.getElementById(id)]));
const canvas = document.getElementById("renderCanvas");
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.shadowMap.enabled = true;
renderer.outputColorSpace = THREE.SRGBColorSpace;
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(38, 1, 0.1, 100);
camera.position.set(8, 5.2, 9);
const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true; controls.maxPolarAngle = Math.PI * .48; controls.minDistance = 7; controls.maxDistance = 18;
const sun = new THREE.DirectionalLight(0xffe6b0, 3.2); sun.position.set(7, 8, 4); sun.castShadow = true; sun.shadow.mapSize.set(2048, 2048); scene.add(sun);
scene.add(new THREE.AmbientLight(0x7f8f91, 1.4));
const ground = new THREE.Mesh(new THREE.CircleGeometry(18, 96), new THREE.MeshStandardMaterial({ color: 0x1f2a22, roughness: 1 })); ground.rotation.x = -Math.PI / 2; ground.receiveShadow = true; scene.add(ground);
const garden = new THREE.Group(); scene.add(garden); const building = new THREE.Group(); scene.add(building);
const materialColors = { thermowood: 0xb98454, black: 0x171717, oak: 0xc69a5f, stone: 0x8f8a7e };
function makeMaterial(color, options = {}) { return new THREE.MeshStandardMaterial({ color, roughness: options.roughness ?? .55, metalness: options.metalness ?? .04, transparent: options.transparent ?? false, opacity: options.opacity ?? 1, emissive: options.emissive ?? 0x000000, emissiveIntensity: options.emissiveIntensity ?? 0 }); }
function makeBox(w, h, d, color, x = 0, y = 0, z = 0, materialOptions = {}) { const mesh = new THREE.Mesh(new THREE.BoxGeometry(w, h, d), makeMaterial(color, materialOptions)); mesh.position.set(x, y, z); mesh.castShadow = true; mesh.receiveShadow = true; return mesh; }
function addSlattedWall(group, width, height, depth, color, z, side = "front", xOffset = 0) { const count = Math.max(14, Math.round(width * 5)); const slatWidth = width / count * .58; const step = width / count; for (let i = 0; i < count; i += 1) { const x = -width / 2 + step * i + step / 2; const slat = new THREE.Mesh(new THREE.BoxGeometry(slatWidth, height, .055), makeMaterial(color, { roughness: .72 })); slat.position.set(x + xOffset, height / 2, z); slat.castShadow = true; slat.receiveShadow = true; group.add(slat); } if (side !== "back") group.add(makeBox(width, .06, .06, 0x151713, xOffset, .22, z + .015)); }
function addSideSlats(group, width, height, depth, color, x) { const count = Math.max(10, Math.round(depth * 5)); const slatDepth = depth / count * .58; const step = depth / count; for (let i = 0; i < count; i += 1) { const z = -depth / 2 + step * i + step / 2; const slat = new THREE.Mesh(new THREE.BoxGeometry(.055, height, slatDepth), makeMaterial(color, { roughness: .72 })); slat.position.set(x, height / 2, z); slat.castShadow = true; slat.receiveShadow = true; group.add(slat); } }
function addFrame(group, width, height, z) { const frameColor = state.windowStyle === "rhythm" ? 0x2c302c : 0x080909; const y = 1.65; group.add(makeBox(width + .16, .08, .11, frameColor, 0, y + height / 2, z)); group.add(makeBox(width + .16, .08, .11, frameColor, 0, y - height / 2, z)); group.add(makeBox(.08, height + .12, .11, frameColor, -width / 2, y, z)); group.add(makeBox(.08, height + .12, .11, frameColor, width / 2, y, z)); if (state.windowStyle === "rhythm") for (let x = -width / 2 + width / 4; x < width / 2; x += width / 4) group.add(makeBox(.045, height, .12, frameColor, x, y, z + .01)); }
function addGardenContext(w, d) { garden.clear(); const poolEdge = makeBox(Math.max(3.6, w * .72), .09, 2.5, 0xd8d1c4, 0, .055, d / 2 + 3.3, { roughness: .62 }); garden.add(poolEdge); const pool = new THREE.Mesh(new THREE.BoxGeometry(Math.max(3.2, w * .68), .08, 2.2), makeMaterial(0x4aa6b7, { roughness: .08, metalness: .02, transparent: true, opacity: .78 })); pool.position.set(0, .11, d / 2 + 3.3); pool.receiveShadow = true; garden.add(pool); for (let i = 0; i < 18; i += 1) { const angle = i / 18 * Math.PI * 2; const radius = 10 + (i % 3); const trunk = makeBox(.12, .75, .12, 0x5d442e, Math.cos(angle) * radius, .38, Math.sin(angle) * radius); const crown = new THREE.Mesh(new THREE.DodecahedronGeometry(.55 + (i % 4) * .05), makeMaterial(i % 2 ? 0x4f684f : 0x6d8060, { roughness: .9 })); crown.position.set(trunk.position.x, .98, trunk.position.z); crown.castShadow = true; garden.add(trunk, crown); } }
function rebuild3D() { building.clear(); const w = state.width; const d = state.depth; const h = state.buildingType === "carport" ? 2.5 : 3; const color = materialColors[state.material]; building.add(makeBox(w + .65, .18, d + .65, 0x191b18, 0, .09, 0)); const interior = makeBox(w - .34, .08, d - .34, 0xc7a36b, 0, .23, 0, { roughness: .82 }); building.add(interior); addSlattedWall(building, w, h, d, color, -d / 2 - .035, "back"); addSideSlats(building, w, h, d, color, -w / 2 - .035); addSideSlats(building, w, h, d, color, w / 2 + .035); const glassWidth = Math.max(1.2, w * state.glass / 100); const glass = new THREE.Mesh(new THREE.BoxGeometry(glassWidth, 2.12, .075), makeMaterial(0xa8d7ea, { roughness: .02, metalness: .04, transparent: true, opacity: .42 })); glass.position.set(0, 1.62, d / 2 + .06); building.add(glass); addFrame(building, glassWidth, 2.12, d / 2 + .11); const solidLeft = Math.max(.2, (w - glassWidth) / 2 - .16); if (solidLeft > .32) { addSlattedWall(building, solidLeft, h, d, color, d / 2 + .04, "front", -glassWidth / 2 - solidLeft / 2 - .12); addSlattedWall(building, solidLeft, h, d, color, d / 2 + .04, "front", glassWidth / 2 + solidLeft / 2 + .12); } const beamColor = state.material === "black" ? 0x080909 : 0x2a2118; [[-w / 2 - .12, d / 2 + .1], [w / 2 + .12, d / 2 + .1], [-w / 2 - .12, -d / 2 - .1], [w / 2 + .12, -d / 2 - .1]].forEach(([x, z]) => building.add(makeBox(.18, h + .25, .18, beamColor, x, (h + .25) / 2, z))); building.add(makeBox(w + .55, .18, .2, beamColor, 0, h + .04, d / 2 + .12)); building.add(makeBox(w + .55, .18, .2, beamColor, 0, h + .04, -d / 2 - .12)); if (state.roof === "gable") { const roof = new THREE.Mesh(new THREE.ConeGeometry(Math.max(w, d) * .66, 1.25, 4), makeMaterial(0x2b302d, { roughness: .72 })); roof.rotation.y = Math.PI / 4; roof.scale.z = d / w; roof.position.y = h + .58; roof.castShadow = true; building.add(roof); } else { const over = state.roof === "canopy" ? 1.5 : .55; building.add(makeBox(w + over, .28, d + over, 0x202421, 0, h + .2, 0)); const warmLine = makeBox(w + over - .5, .035, .035, 0xffc46f, 0, h + .02, d / 2 + over / 2 - .18); warmLine.material.emissive = new THREE.Color(0xff9e4a); warmLine.material.emissiveIntensity = state.night ? 2.8 : .65; building.add(warmLine); } if (state.activeModules.has("terrace")) { const terrace = makeBox(w + 1.8, .16, 2.25, 0x8b6840, 0, .08, d / 2 + 1.12, { roughness: .86 }); building.add(terrace); for (let i = 0; i < 12; i += 1) building.add(makeBox(w + 1.76, .02, .025, 0x5f452c, 0, .18, d / 2 + .2 + i * .17)); } if (state.activeModules.has("carport") || state.buildingType === "carport") building.add(makeBox(3.4, 2.5, d, 0x1c1f1d, w / 2 + 2.2, 1.25, 0)); if (state.activeModules.has("sauna")) building.add(makeBox(1.5, 2.2, 1.7, 0x4b3528, -w / 2 + .9, 1.1, -d / 2 + .9)); addGardenContext(w, d); }
function price() { const area = state.width * state.depth; const typeBase = { poolhouse: 1350, office: 1650, gardenroom: 1280, guesthouse: 2100, carport: 780, storage: 720 }[state.buildingType]; const roofFactor = { flat: 1, gable: 1.16, canopy: 1.24 }[state.roof]; const materialFactor = { thermowood: 1.08, black: 1.18, oak: 1.12, stone: 1.32 }[state.material]; const glassPremium = area * state.glass * 10.5; const moduleTotal = [...state.activeModules].reduce((sum, id) => sum + modules.find((m) => m[0] === id)[2], 0); return Math.round(area * typeBase * roofFactor * materialFactor + glassPremium + moduleTotal); }
function euro(value) { return value.toLocaleString("nl-BE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }); }
function renderChoices() { els.moodChoices.innerHTML = Object.entries(moods).map(([id, mood]) => `<button class="choice ${state.mood === id ? "active" : ""}" data-mood="${id}" type="button"><strong>${mood.label}</strong><span>${mood.sub}</span></button>`).join(""); els.moduleChoices.innerHTML = modules.map(([id, label, add]) => `<button class="module ${state.activeModules.has(id) ? "active" : ""}" data-module="${id}" type="button">${label} · +${euro(add)}</button>`).join(""); }
function recommendation(total) { const overBudget = total - state.budget; if (overBudget > 0) return ["AI ziet een premium ontwerp, maar het budget staat onder druk.", `Vervang natuursteen of verminder glas lichtjes: je behoudt dezelfde uitstraling voor ongeveer ${Math.min(18, Math.round(overBudget / total * 100 + 7))}% minder budget.`]; if (state.glass > 60) return ["Meer glas maakt deze ruimte luxueuzer en lichter.", "Plaats de grootste glaspartij op de zuid- of westzijde voor avondlicht. Combineer dit met een dakoversteek om oververhitting te vermijden."]; if (state.activeModules.has("sauna")) return ["De sauna maakt dit ontwerp emotioneel sterker.", "Houd de buitenzijde rustig: zwarte accenten, warm hout en indirecte verlichting zorgen voor een private wellnesservaring."]; return ["Dit ontwerp voelt rustig, architecturaal en verkoopbaar.", "De verhouding tussen volume, glas en materiaal is in balans. Een subtiele oversteek verhoogt de premium uitstraling en beschermt het hout."]; }
function renderUI() { const mood = moods[state.mood]; const total = price(); const over = total - state.budget; const [headline, text] = recommendation(total); els.totalPrice.textContent = euro(total); els.priceDelta.textContent = over > 0 ? `${euro(over)} boven budget. AI toont een zachter alternatief.` : `${euro(state.budget - total)} ruimte voor upgrades zonder verkoopdruk.`; els.conceptTitle.textContent = mood.title; els.dimensions.textContent = `${state.width} x ${state.depth} m`; els.aiHeadline.textContent = headline; els.aiText.textContent = text; els.budgetFit.textContent = over > 0 ? `${euro(over)} boven budget` : "Binnen budget"; els.upgrade.textContent = state.roof === "canopy" ? "Indirecte LED-lijn" : "Lamellendak"; els.saving.textContent = state.material === "stone" ? "Thermowood -18%" : "Slim glasritme -12%"; els.lifestyleVisual.style.backgroundImage = `linear-gradient(180deg, rgba(0,0,0,.05), rgba(0,0,0,.42)), url(${mood.image})`; els.lifestyleText.textContent = `Een ${mood.label.toLowerCase()} ${state.buildingType} van ${state.width * state.depth} m², ontworpen rond ${els.feeling.options[els.feeling.selectedIndex].text.toLowerCase()}.`; rebuild3D(); }
function syncFromMood(id) { state.mood = id; state.material = moods[id].material; state.roof = moods[id].roof; els.material.value = state.material; els.roof.value = state.roof; }
function wire() { renderChoices(); document.addEventListener("click", (event) => { const moodButton = event.target.closest("[data-mood]"); const moduleButton = event.target.closest("[data-module]"); if (moodButton) syncFromMood(moodButton.dataset.mood); if (moduleButton) { const id = moduleButton.dataset.module; state.activeModules.has(id) ? state.activeModules.delete(id) : state.activeModules.add(id); } if (moodButton || moduleButton) { renderChoices(); renderUI(); } }); ["feeling", "buildingType", "roof", "material", "windowStyle"].forEach((id) => els[id].addEventListener("change", () => { state[id] = els[id].value; renderUI(); })); ["width", "depth", "glass", "budget"].forEach((id) => els[id].addEventListener("input", () => { state[id] = Number(els[id].value); renderUI(); })); els.dayNightBtn.addEventListener("click", () => { state.night = !state.night; sun.intensity = state.night ? .65 : 3.2; scene.background = new THREE.Color(state.night ? 0x050607 : 0x000000); renderUI(); }); els.rotateBtn.addEventListener("click", () => { state.rotate = !state.rotate; }); els.arBtn.addEventListener("click", () => alert("AR-view concept: koppel WebXR en plaats dit model op schaal in de tuin via de smartphonecamera.")); els.shareBtn.addEventListener("click", shareDesign); els.saveBtn.addEventListener("click", shareDesign); els.compareBtn.addEventListener("click", () => alert("Variant opgeslagen: AI kan nu budget, premium en wellness naast elkaar tonen.")); els.appointmentBtn.addEventListener("click", () => alert("Volgende stap: plan een showroombezoek of videocall met een architecturaal adviseur.")); }
function shareDesign() { const summary = `${moods[state.mood].title} · ${state.width} x ${state.depth} m · ${euro(price())}`; navigator.clipboard?.writeText(summary); alert(`Ontwerp klaar om te delen:\n${summary}`); }
function resize() { const { clientWidth, clientHeight } = canvas; renderer.setSize(clientWidth, clientHeight, false); camera.aspect = clientWidth / clientHeight; camera.updateProjectionMatrix(); }
function animate() { resize(); if (state.rotate) building.rotation.y += .003; controls.update(); renderer.render(scene, camera); requestAnimationFrame(animate); }
wire(); renderUI(); animate();
