import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";

const moods = {
  japandi: { title: "Japandi Poolhouse Retreat", label: "Japandi calm", sub: "stilte, balans, warm minimalisme", material: "thermowood", roof: "flat", image: "https://images.unsplash.com/photo-1600566753151-384129cf4e3e?auto=format&fit=crop&w=900&q=80" },
  villa: { title: "Luxury Villa Outdoor Room", label: "Luxe villa", sub: "status, avondlicht, ontvangst", material: "black", roof: "canopy", image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80" },
  rural: { title: "Landelijke Eik-Douglas Lodge", label: "Landelijk", sub: "authentiek, warm, familiaal", material: "oak", roof: "gable", image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80" },
  wellness: { title: "Private Wellness Garden Suite", label: "Wellness", sub: "sauna, rust, zachte verlichting", material: "stone", roof: "flat", image: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=900&q=80" }
};
const modules = [["terrace", "Terras", 4200], ["storage", "Berging", 5200], ["sauna", "Sauna", 11800], ["kitchen", "Buitenkeuken", 8900], ["bike", "Fietsenstalling", 2600], ["lounge", "Lounge", 6400], ["carport", "Carport", 7600]];
const state = { mood: "japandi", feeling: "calm", buildingType: "poolhouse", roof: "flat", material: "thermowood", windowStyle: "panoramic", width: 6, depth: 4, glass: 45, budget: 42000, activeModules: new Set(["terrace", "lounge"]), night: false, rotate: true };
const ids = ["moodChoices", "moduleChoices", "feeling", "width", "depth", "glass", "budget", "buildingType", "roof", "material", "windowStyle", "totalPrice", "priceDelta", "conceptTitle", "dimensions", "aiHeadline", "aiText", "budgetFit", "upgrade", "saving", "lifestyleVisual", "lifestyleText", "dayNightBtn", "rotateBtn", "shareBtn", "saveBtn", "compareBtn", "appointmentBtn", "arBtn"];
const els = Object.fromEntries(ids.map((id) => [id, document.getElementById(id)]));
const canvas = document.getElementById("renderCanvas");
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.shadowMap.enabled = true;
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(38, 1, 0.1, 100);
camera.position.set(8, 5.2, 9);
const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.maxPolarAngle = Math.PI * .48;
controls.minDistance = 7;
controls.maxDistance = 18;
const sun = new THREE.DirectionalLight(0xffe6b0, 3.2);
sun.position.set(7, 8, 4);
sun.castShadow = true;
scene.add(sun);
scene.add(new THREE.AmbientLight(0x7f8f91, 1.4));
const ground = new THREE.Mesh(new THREE.CircleGeometry(18, 96), new THREE.MeshStandardMaterial({ color: 0x283126, roughness: 1 }));
ground.rotation.x = -Math.PI / 2;
ground.receiveShadow = true;
scene.add(ground);
const building = new THREE.Group();
scene.add(building);
const materialColors = { thermowood: 0xb98454, black: 0x171717, oak: 0xc69a5f, stone: 0x8f8a7e };
function makeBox(w, h, d, color, x = 0, y = 0, z = 0) { const mesh = new THREE.Mesh(new THREE.BoxGeometry(w, h, d), new THREE.MeshStandardMaterial({ color, roughness: .58, metalness: .04 })); mesh.position.set(x, y, z); mesh.castShadow = true; mesh.receiveShadow = true; return mesh; }
function rebuild3D() { building.clear(); const w = state.width; const d = state.depth; const h = state.buildingType === "carport" ? 2.5 : 3; building.add(makeBox(w, h, d, materialColors[state.material], 0, h / 2, 0)); const glassWidth = Math.max(1.2, w * state.glass / 100); const glass = makeBox(glassWidth, 2.1, .08, 0x9fd8ff, 0, 1.65, d / 2 + .045); glass.material.transparent = true; glass.material.opacity = .46; building.add(glass); if (state.roof === "gable") { const roof = new THREE.Mesh(new THREE.ConeGeometry(Math.max(w, d) * .66, 1.25, 4), new THREE.MeshStandardMaterial({ color: 0x2b302d, roughness: .72 })); roof.rotation.y = Math.PI / 4; roof.scale.z = d / w; roof.position.y = h + .58; roof.castShadow = true; building.add(roof); } else { const over = state.roof === "canopy" ? 1.5 : .55; building.add(makeBox(w + over, .28, d + over, 0x202421, 0, h + .2, 0)); } if (state.activeModules.has("terrace")) building.add(makeBox(w + 1.6, .16, 2.1, 0x8b6840, 0, .08, d / 2 + 1.08)); if (state.activeModules.has("carport") || state.buildingType === "carport") building.add(makeBox(3.4, 2.5, d, 0x1c1f1d, w / 2 + 2.2, 1.25, 0)); if (state.activeModules.has("sauna")) building.add(makeBox(1.5, 2.2, 1.7, 0x4b3528, -w / 2 + .9, 1.1, -d / 2 + .9)); }
function price() { const area = state.width * state.depth; const typeBase = { poolhouse: 1350, office: 1650, gardenroom: 1280, guesthouse: 2100, carport: 780, storage: 720 }[state.buildingType]; const roofFactor = { flat: 1, gable: 1.16, canopy: 1.24 }[state.roof]; const materialFactor = { thermowood: 1.08, black: 1.18, oak: 1.12, stone: 1.32 }[state.material]; const glassPremium = area * state.glass * 10.5; const moduleTotal = [...state.activeModules].reduce((sum, id) => sum + modules.find((m) => m[0] === id)[2], 0); return Math.round(area * typeBase * roofFactor * materialFactor + glassPremium + moduleTotal); }
function euro(value) { return value.toLocaleString("nl-BE", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }); }
function renderChoices() { els.moodChoices.innerHTML = Object.entries(moods).map(([id, mood]) => `<button class="choice ${state.mood === id ? "active" : ""}" data-mood="${id}" type="button"><strong>${mood.label}</strong><span>${mood.sub}</span></button>`).join(""); els.moduleChoices.innerHTML = modules.map(([id, label, add]) => `<button class="module ${state.activeModules.has(id) ? "active" : ""}" data-module="${id}" type="button">${label} · +${euro(add)}</button>`).join(""); }
function recommendation(total) { const overBudget = total - state.budget; if (overBudget > 0) return ["AI ziet een premium ontwerp, maar het budget staat onder druk.", `Vervang natuursteen of verminder glas lichtjes: je behoudt dezelfde uitstraling voor ongeveer ${Math.min(18, Math.round(overBudget / total * 100 + 7))}% minder budget.`]; if (state.glass > 60) return ["Meer glas maakt deze ruimte luxueuzer en lichter.", "Plaats de grootste glaspartij op de zuid- of westzijde voor avondlicht. Combineer dit met een dakoversteek om oververhitting te vermijden."]; if (state.activeModules.has("sauna")) return ["De sauna maakt dit ontwerp emotioneel sterker.", "Houd de buitenzijde rustig: zwarte accenten, warm hout en indirecte verlichting zorgen voor een private wellnesservaring."]; return ["Dit ontwerp voelt rustig, architecturaal en verkoopbaar.", "De verhouding tussen volume, glas en materiaal is in balans. Een subtiele oversteek verhoogt de premium uitstraling en beschermt het hout."]; }
function renderUI() { const mood = moods[state.mood]; const total = price(); const over = total - state.budget; const [headline, text] = recommendation(total); els.totalPrice.textContent = euro(total); els.priceDelta.textContent = over > 0 ? `${euro(over)} boven budget. AI toont een zachter alternatief.` : `${euro(state.budget - total)} ruimte voor upgrades zonder verkoopdruk.`; els.conceptTitle.textContent = mood.title; els.dimensions.textContent = `${state.width} x ${state.depth} m`; els.aiHeadline.textContent = headline; els.aiText.textContent = text; els.budgetFit.textContent = over > 0 ? `${euro(over)} boven budget` : "Binnen budget"; els.upgrade.textContent = state.roof === "canopy" ? "Indirecte LED-lijn" : "Lamellendak"; els.saving.textContent = state.material === "stone" ? "Thermowood -18%" : "Slim glasritme -12%"; els.lifestyleVisual.style.backgroundImage = `linear-gradient(180deg, rgba(0,0,0,.05), rgba(0,0,0,.42)), url(${mood.image})`; els.lifestyleText.textContent = `Een ${mood.label.toLowerCase()} ${state.buildingType} van ${state.width * state.depth} m², ontworpen rond ${els.feeling.options[els.feeling.selectedIndex].text.toLowerCase()}.`; rebuild3D(); }
function syncFromMood(id) { state.mood = id; state.material = moods[id].material; state.roof = moods[id].roof; els.material.value = state.material; els.roof.value = state.roof; }
function wire() { renderChoices(); document.addEventListener("click", (event) => { const moodButton = event.target.closest("[data-mood]"); const moduleButton = event.target.closest("[data-module]"); if (moodButton) syncFromMood(moodButton.dataset.mood); if (moduleButton) { const id = moduleButton.dataset.module; state.activeModules.has(id) ? state.activeModules.delete(id) : state.activeModules.add(id); } if (moodButton || moduleButton) { renderChoices(); renderUI(); } }); ["feeling", "buildingType", "roof", "material", "windowStyle"].forEach((id) => els[id].addEventListener("change", () => { state[id] = els[id].value; renderUI(); })); ["width", "depth", "glass", "budget"].forEach((id) => els[id].addEventListener("input", () => { state[id] = Number(els[id].value); renderUI(); })); els.dayNightBtn.addEventListener("click", () => { state.night = !state.night; sun.intensity = state.night ? .65 : 3.2; scene.background = new THREE.Color(state.night ? 0x050607 : 0x000000); }); els.rotateBtn.addEventListener("click", () => { state.rotate = !state.rotate; }); els.arBtn.addEventListener("click", () => alert("AR-view concept: koppel WebXR en plaats dit model op schaal in de tuin via de smartphonecamera.")); els.shareBtn.addEventListener("click", shareDesign); els.saveBtn.addEventListener("click", shareDesign); els.compareBtn.addEventListener("click", () => alert("Variant opgeslagen: AI kan nu budget, premium en wellness naast elkaar tonen.")); els.appointmentBtn.addEventListener("click", () => alert("Volgende stap: plan een showroombezoek of videocall met een architecturaal adviseur.")); }
function shareDesign() { const summary = `${moods[state.mood].title} · ${state.width} x ${state.depth} m · ${euro(price())}`; navigator.clipboard?.writeText(summary); alert(`Ontwerp klaar om te delen:\n${summary}`); }
function resize() { const { clientWidth, clientHeight } = canvas; renderer.setSize(clientWidth, clientHeight, false); camera.aspect = clientWidth / clientHeight; camera.updateProjectionMatrix(); }
function animate() { resize(); if (state.rotate) building.rotation.y += .003; controls.update(); renderer.render(scene, camera); requestAnimationFrame(animate); }
wire(); renderUI(); animate();
